id: I81CF381A
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-04-17T21:44:36+00:00'
last_modified: '2022-06-14T08:24:07.420053+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W2DB4578
  title: གསུང་འབུམ། གཞན་ཕན་ཆོས་ཀྱི་སྣང་བ
  author: ''
  base:
    C88D:
      image_group_id: I1PD35546
      title: ''
      total_pages: ''
      order: 1
      base_file: C88D.txt
    7C57:
      image_group_id: I1PD35547
      title: ''
      total_pages: ''
      order: 2
      base_file: 7C57.txt
    4E8F:
      image_group_id: I1PD35548
      title: ''
      total_pages: ''
      order: 3
      base_file: 4E8F.txt
    3EB4:
      image_group_id: I1PD35549
      title: ''
      total_pages: ''
      order: 4
      base_file: 3EB4.txt
    9A3A:
      image_group_id: I1PD35550
      title: ''
      total_pages: ''
      order: 5
      base_file: 9A3A.txt
    '1157':
      image_group_id: I1PD35551
      title: ''
      total_pages: ''
      order: 6
      base_file: 1157.txt
    143C:
      image_group_id: I1PD35552
      title: ''
      total_pages: ''
      order: 7
      base_file: 143C.txt
    8A88:
      image_group_id: I1PD35553
      title: ''
      total_pages: ''
      order: 8
      base_file: 8A88.txt
    B4C0:
      image_group_id: I1PD35554
      title: ''
      total_pages: ''
      order: 9
      base_file: B4C0.txt
    4C04:
      image_group_id: I1PD35555
      title: ''
      total_pages: ''
      order: 10
      base_file: 4C04.txt
    0882:
      image_group_id: I1PD35556
      title: ''
      total_pages: ''
      order: 11
      base_file: 0882.txt
    0F34:
      image_group_id: I1PD35557
      title: ''
      total_pages: ''
      order: 12
      base_file: 0F34.txt
    6DFA:
      image_group_id: I1PD35558
      title: ''
      total_pages: ''
      order: 13
      base_file: 6DFA.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
